# Generated by Django 3.1.1 on 2020-09-13 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("iam", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("last_edited_time", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(blank=True, max_length=1500)),
                ("motes", models.CharField(blank=True, max_length=1500)),
                ("content", models.CharField(blank=True, max_length=2500)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="iam.tenant"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Sponsership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("last_edited_time", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(blank=True, max_length=1500)),
                ("motes", models.CharField(blank=True, max_length=1500)),
                (
                    "sponsorship_type",
                    models.IntegerField(
                        choices=[(0, "Dedicated"), (1, "Shoutout")], default=0
                    ),
                ),
                ("no_of_videos", models.PositiveIntegerField(blank=True, null=True)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("total_amount", models.PositiveIntegerField(blank=True, null=True)),
                ("agreement", models.TextField(blank=True, max_length=2500)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="iam.tenant"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("last_edited_time", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(blank=True, max_length=1500)),
                ("motes", models.CharField(blank=True, max_length=1500)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Todo"),
                            (1, "Planning"),
                            (2, "Scripting"),
                            (3, "Production"),
                            (4, "Editing"),
                            (5, "Completed"),
                            (6, "Published"),
                        ],
                        default=0,
                    ),
                ),
                ("script", models.TextField(blank=True, max_length=2500)),
                (
                    "sponsorships",
                    models.ManyToManyField(
                        blank=True, null=True, to="productivity.Sponsership"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="iam.tenant"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Idea",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("last_edited_time", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(blank=True, max_length=1500)),
                ("motes", models.CharField(blank=True, max_length=1500)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="iam.tenant"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
